runtime: nodejs22
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

env_variables:
  DB_HOST: "hospital-saint-michel-460809:southamerica-east1:dbsaintmichel"
  DB_USER: "root"
  DB_PASSWORD: "kbN2+j_NHeN(v*/a"
  DB_NAME: "dbsaintmichel"

beta_settings:
  cloud_sql_instances: hospital-saint-michel-460809:southamerica-east1:dbsaintmichel

entrypoint: node src/server.js
